### ISSUE TITLE
Unable to transform arrow inside class property

### ISSUE THREAD

**Issue by adminy** [alex8088/electron-vite#156]
> **Warning**
> Similar issue found here: https://github.com/alex8088/electron-vite/issues/60
Taking bytecode plugin out from the config, fixes the problem.

### Describe the bug

When I run `electron-vite dev --watch`, the application runs fine.
But when its run with `electron-vite build` I get the following:

```javascript
vite v4.3.5 building for production...
✓ 277 modules transformed.
rendering chunks (3)...[vite:bytecode] unknown file: Unable to transform arrow inside class property
  12144 |     }
  12145 |     // conditionally set private methods related to TTL
> 12146 |     #updateItemAge = () => { };
        |                      ^^^^^^^^^
  12147 |     #statusTTL = () => { };
  12148 |     #setItemTTL = () => { };
  12149 |     /* c8 ignore stop */
✓ 0 bundles compiled into bytecode.
✓ built in 1.66s
error during build:
SyntaxError: unknown file: Unable to transform arrow inside class property
  12144 |     }
  12145 |     // conditionally set private methods related to TTL
> 12146 |     #updateItemAge = () => { };
        |                      ^^^^^^^^^
  12147 |     #statusTTL = () => { };
  12148 |     #setItemTTL = () => { };
  12149 |     /* c8 ignore stop */
    at File.buildCodeFrameError (/Users/adminy/project/node_modules/@babel/core/lib/transformation/file/file.js:205:12)
    at NodePath.buildCodeFrameError (/Users/adminy/project/node_modules/@babel/traverse/lib/path/index.js:105:21)
    at hoistFunctionEnvironment (/Users/adminy/project/node_modules/@babel/traverse/lib/path/conversion.js:171:20)
    at NodePath.arrowFunctionToExpression (/Users/adminy/project/node_modules/@babel/traverse/lib/path/conversion.js:121:7)
    at PluginPass.ArrowFunctionExpression (/Users/adminy/project/node_modules/@babel/plugin-transform-arrow-functions/lib/index.js:18:16)
    at newFn (/Users/adminy/project/node_modules/@babel/traverse/lib/visitors.js:149:21)
    at NodePath._call (/Users/adminy/project/node_modules/@babel/traverse/lib/path/context.js:45:20)
    at NodePath.call (/Users/adminy/project/node_modules/@babel/traverse/lib/path/context.js:35:17)
    at NodePath.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/path/context.js:81:31)
    at TraversalContext.visitQueue (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/Users/adminy/project/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/path/context.js:87:52)
    at TraversalContext.visitQueue (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/Users/adminy/project/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/path/context.js:87:52)
    at TraversalContext.visitQueue (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/Users/adminy/project/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/path/context.js:87:52)
    at TraversalContext.visitQueue (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/Users/adminy/project/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/path/context.js:87:52)
    at TraversalContext.visitQueue (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/Users/adminy/project/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/path/context.js:87:52)
    at TraversalContext.visitQueue (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/Users/adminy/project/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/path/context.js:87:52)
    at TraversalContext.visitQueue (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/Users/adminy/project/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/Users/adminy/project/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at traverse (/Users/adminy/project/node_modules/@babel/traverse/lib/index.js:49:34)
    at transformFile (/Users/adminy/project/node_modules/@babel/core/lib/transformation/index.js:81:29)
    at transformFile.next (<anonymous>)
    at run (/Users/adminy/project/node_modules/@babel/core/lib/transformation/index.js:24:12)
    at run.next (<anonymous>)
    at transform (/Users/adminy/project/node_modules/@babel/core/lib/transform.js:22:41)
    at transform.next (<anonymous>)
```

My `electron.vite.config.mjs` looks like this:
```javascript
import { defineConfig, externalizeDepsPlugin, bytecodePlugin } from 'electron-vite'
import { svelte } from '@sveltejs/vite-plugin-svelte'
export default defineConfig({
  main: { plugins: [externalizeDepsPlugin(), bytecodePlugin()] },
  preload: { plugins: [externalizeDepsPlugin(), bytecodePlugin()] },
  renderer: {
    plugins: [svelte()],
    define: { global: {}, 'process.env': process.env }
  }
})
```

I thought it was a babel issue https://github.com/babel/babel/issues/15613
but now I'm not so sure...

### Electron-Vite Version

1.0.22

### Electron Version

24.2.0

### Vite Version

4.3.4

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.
There was a similar issue actually, https://github.com/alex8088/electron-vite/issues/60
related to bytecode plugin. Taking that out from the config, fixes the problem.

**Comment by alex8088** [comment]
Bytecode protection requires converting `arrow functions` to `normal functions`.

```ts
class A {
  handle = (x = 0) => {
    console.log(x);
  };
}
```

The above example has a problem with conversion. This is a related bug of babel. The solution is to use normal functions or as follows:

```ts
class A {
  async handle(x = 0) {
    console.log(x);
  };
}
```

**Comment by adminy** [comment]
But I don't even have classes in my code ...

**Comment by alex8088** [comment]
Install related modules in `deps`.

**Comment by adminy** [comment]
I did that, now its just saying:
![Screenshot 2023-05-08 at 19 06 58](https://user-images.githubusercontent.com/22717869/236898353-d3e75500-a8b4-4fdd-b5cd-e637beb79fa9.png)

**Comment by philjones88** [comment]
in my case, it's this package https://github.com/megahertz/electron-log/blob/master/src/node/EventLogger.js#L8 that breaks my build

**Comment by zhimingzhang123** [comment]
> in my case, it's this package [megahertz/electron-log@`master`/src/node/EventLogger.js#L8](https://github.com/megahertz/electron-log/blob/master/src/node/EventLogger.js?rgh-link-date=2024-02-06T16%3A24%3A15Z#L8) that breaks my build

So, how did you ultimately solve it？

**Comment by duyixian1234** [comment]
> > in my case, it's this package [megahertz/electron-log@`master`/src/node/EventLogger.js#L8](https://github.com/megahertz/electron-log/blob/master/src/node/EventLogger.js?rgh-link-date=2024-02-06T16%3A24%3A15Z#L8) that breaks my build
> 
> @philjones88 So, how did you ultimately solve it？

I mannuly modified source code for electron-log, and it worked
`node_modules\electron-log\src\node\EventLogger.js`
![image](https://github.com/alex8088/electron-vite/assets/3953615/c85fd55f-bb9f-4a39-b34b-b97f8d0f4efc)
![image](https://github.com/alex8088/electron-vite/assets/3953615/76d96b3b-51e3-41c9-b02d-512da2bb5a23)

**Comment by zhimingzhang123** [comment]
@duyixian1234 thank you, it works well😃
