### ISSUE TITLE
打包时遇到的一个问题，请教下，是我的版本太高了么？

### ISSUE THREAD

**Issue by dengwl** [alex8088/electron-vite#172]
### Clear and concise description of the problem

TypeError: documentRegistry.getKeyForCompilationSettings is not a function
    at synchronizeHostData (D:\PAD\suppliersclient\node_modules\.store\typescript@4.9.5\node_modules\typescript\lib\typescript.js:169318:62)
    at Object.getProgram (D:\PAD\suppliersclient\node_modules\.store\typescript@4.9.5\node_modules\typescript\lib\typescript.js:169449:13)
    at Object.createProgram (D:\PAD\suppliersclient\node_modules\.store\vue-tsc@1.4.4\node_modules\vue-tsc\out\index.js:65:27)
    at Object.createProgram (D:\PAD\suppliersclient\node_modules\.store\typescript@4.9.5\node_modules\typescript\lib\tsc.js:98760:229)
    at performCompilation (D:\PAD\suppliersclient\node_modules\.store\typescript@4.9.5\node_modules\typescript\lib\tsc.js:107870:26)
    at executeCommandLineWorker (D:\PAD\suppliersclient\node_modules\.store\typescript@4.9.5\node_modules\typescript\lib\tsc.js:107744:17)
    at Object.executeCommandLine (D:\PAD\suppliersclient\node_modules\.store\typescript@4.9.5\node_modules\typescript\lib\tsc.js:107789:20)
    at Object.<anonymous> (D:\PAD\suppliersclient\node_modules\.store\typescript@4.9.5\node_modules\typescript\lib\tsc.js:108187:4)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)

Node.js v18.11.0

### Suggested solution

打包时报这个错误，开发环境没问题。请教下这个问题我是应该降版本么？

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
升级vue-tsc

**Comment by dengwl** [comment]
> 升级vue-tsc

![image](https://github.com/alex8088/electron-vite/assets/19411201/32fada02-c283-4a6f-9f2b-dfee0d0c0c67)
1.6.5了

**Comment by alex8088** [comment]
https://github.com/vuejs/language-tools/tree/master/packages/vue-tsc

Vue 3 command line Type-Checking tool base on IDE plugin [Volar](https://github.com/vuejs/language-tools).

**Comment by dengwl** [comment]
> https://github.com/vuejs/language-tools/tree/master/packages/vue-tsc
> 
> Vue 3 command line Type-Checking tool base on IDE plugin [Volar](https://github.com/vuejs/language-tools).
> 
> 在相同node版本下，并未发现此问题，如果你还是没有解决，建议将此问题反馈给vue-t

**Comment by dengwl** [comment]
点错了，electron是22.3.10么

> > https://github.com/vuejs/language-tools/tree/master/packages/vue-tsc
> > Vue 3 command line Type-Checking tool base on IDE plugin [Volar](https://github.com/vuejs/language-tools).
> > 在相同node版本下，并未发现此问题，如果你还是没有解决，建议将此问题反馈给vue-t

你测试时的electron版本是22.3.10吗？

**Comment by alex8088** [comment]
这和electron无关，仅仅是TS类型检查

**Comment by alex8088** [comment]
你也可以使用create-vue创建一个ts项目，执行type-check脚本，看看是不是有同样的问题
