### ISSUE TITLE
无法自定义 renderer 的 root 和 build.lib.entry

### ISSUE THREAD

**Issue by guoyunhe** [alex8088/electron-vite#256]
### Describe the bug

https://github.com/guoyunhe/mui-app-template

配置如下：

```ts
import { defineConfig, externalizeDepsPlugin } from 'electron-vite';
import config from './vite.config';

export default defineConfig({
  main: {
    build: {
      lib: {
        entry: './src/electron/main/index.ts',
      },
    },
    plugins: [externalizeDepsPlugin()],
  },
  preload: {
    build: {
      lib: {
        entry: './src/electron/preload/index.ts',
      },
    },
    plugins: [externalizeDepsPlugin()],
  },
  renderer: {
    ...config,
    root: './',
    build: {
      lib: {
        entry: './index.html',
      },
    },
  },
});
```

运行时报错：

```
index.html file is not found in /src/renderer directory
error during start dev server and electron app:
Error: build rollupOptions input field required for the electron vite renderer config
    at configResolved (/home/guo/git/mui-app-template/node_modules/.pnpm/electron-vite@1.0.27_vite@4.4.9/node_modules/electron-vite/dist/chunks/lib-a7bfaa24.js:423:27)
    at file:///home/guo/git/mui-app-template/node_modules/.pnpm/vite@4.4.9_@types+node@20.5.0/node_modules/vite/dist/node/chunks/dep-df561101.js:65946:28
    at Array.map (<anonymous>)
    at resolveConfig (file:///home/guo/git/mui-app-template/node_modules/.pnpm/vite@4.4.9_@types+node@20.5.0/node_modules/vite/dist/node/chunks/dep-df561101.js:65946:14)
    at async _createServer (file:///home/guo/git/mui-app-template/node_modules/.pnpm/vite@4.4.9_@types+node@20.5.0/node_modules/vite/dist/node/chunks/dep-df561101.js:64959:20)
    at async createServer (/home/guo/git/mui-app-template/node_modules/.pnpm/electron-vite@1.0.27_vite@4.4.9/node_modules/electron-vite/dist/chunks/lib-3249d76e.js:58:22)
    at async CAC.<anonymous> (/home/guo/git/mui-app-template/node_modules/.pnpm/electron-vite@1.0.27_vite@4.4.9/node_modules/electron-vite/dist/cli.js:56:9)
 ELIFECYCLE  Command failed with exit code 1.
```

### Electron-Vite Version

1.0.27

### Electron Version

26.0.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://cn.electron-vite.org/guide/dev.html#%E8%87%AA%E5%AE%9A%E4%B9%89

**Comment by guoyunhe** [comment]
@alex8088 但是配置这里是写的用 root 和 lib 配置，有点迷惑 https://cn.electron-vite.org/config/#%E5%86%85%E7%BD%AE%E9%85%8D%E7%BD%AE

**Comment by joaobibiano** [comment]
Guys, I love this project but could you please, be more inclusive by using english only?
