### ISSUE TITLE
build:win 报错；

### ISSUE THREAD

**Issue by tom-style** [alex8088/electron-vite#259]
### Describe the bug

通过 npm create @quick-start/electron 创建的项目，安装完依赖后build报错，貌似还可以正常运行；
✓ built in 2.32s
  • electron-builder  version=24.6.3 os=10.0.22621
  • loaded configuration  file=...\electron-app\electron-builder.yml
  • writing effective config  file=dist\builder-effective-config.yaml
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=win32 arch=x64 electron=25.7.0 appOutDir=dist\win-unpacked
  ⨯ Application entry file "out\main\index.js" in the "...\electron-app\dist\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.  failedTask=build stackTrace=Error: Application entry file "out\main\index.js" in the "...\electron-app\dist\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.
    at error (...\electron-app\node_modules\app-builder-lib\src\asar\asarFileChecker.ts:7:12)
    at checkFileInArchive (...\electron-app\node_modules\app-builder-lib\src\asar\asarFileChecker.ts:31:11)
    at WinPackager.checkFileInPackage (...\electron-app\node_modules\app-builder-lib\src\platformPackager.ts:510:7)
    at WinPackager.sanityCheckPackage (...\electron-app\node_modules\app-builder-lib\src\platformPackager.ts:558:5)
    at WinPackager.doPack (...\electron-app\node_modules\app-builder-lib\src\platformPackager.ts:315:5)
    at WinPackager.pack (...\electron-app\node_modules\app-builder-lib\src\platformPackager.ts:136:5)
    at Packager.doBuild (...\electron-app\node_modules\app-builder-lib\src\packager.ts:442:9)
    at executeFinally (...\electron-app\node_modules\builder-util\src\promise.ts:12:14)
    at Packager._build (...\electron-app\node_modules\app-builder-lib\src\packager.ts:376:31)
    at Packager.build (...\electron-app\node_modules\app-builder-lib\src\packager.ts:337:12)
    at executeFinally (...\electron-app\node_modules\builder-util\src\promise.ts:12:14)
 ELIFECYCLE  Command failed with exit code 1.

### Electron-Vite Version

1.0.26

### Electron Version

24.6.2

### Vite Version

4.4.2

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
是否没有构建，就打包程序，无更多信息，无确认是什么问题

**Comment by tom-style** [comment]
> 是否没有构建，就打包程序，无更多信息，无确认是什么问题

经测试程序.exe已经构建,win-unpacked 也已经构建且可以正常运行，最后报了这个错；

**Comment by pot-code** [comment]
> 是否没有构建，就打包程序，无更多信息，无确认是什么问题

@alex8088 electron-builder.yml 配置文件的 files 没有包含 out/main/index.js 就会报这个错误，而且必须要有这一项，通配符行不通
