### ISSUE TITLE
[IDE] Unable to attach the debugger when using Intellij IDEA

### ISSUE THREAD

**Issue by AlexV525** [alex8088/electron-vite#306]
### Describe the bug

1. Setup the project follows the guide from https://cn.electron-vite.org/guide/#%E6%90%AD%E5%BB%BA%E7%AC%AC%E4%B8%80%E4%B8%AA-electron-vite-%E9%A1%B9%E7%9B%AE.
2. Open the IDEA and configure the run configuration as suggested by https://blog.jetbrains.com/webstorm/2016/05/getting-started-with-electron-in-webstorm.
![image](https://github.com/alex8088/electron-vite/assets/15884415/1c3efffa-e9fe-4176-a0f6-514a547e0b69)
3. Click "Debug" to the main process.

The issue can only be reproduced when running "Debug" rather than "Run".

```console
X:\Coding\Garages\something\node_modules\.bin\electron-vite.CMD --sourcemap
Debugger listening on ws://127.0.0.1:58014/6cf03a2c-ba86-44ca-b90c-6d65de44de6f
For help, see: https://nodejs.org/en/docs/inspector
X:\Coding\Garages\something\node_modules\.pnpm\electron-vite@1.0.27_vite@4.4.9\node_modules\electron-vite\dist\chunks\lib-a7bfaa24.js:250
                        throw new Error('build entry field required for the electron vite main config');
                              ^


Error: build entry field required for the electron vite main config
    at configResolved (X:\Coding\Garages\something\node_modules\.pnpm\electron-vite@1.0.27_vite@4.4.9\node_modules\electron-vite\dist\chunks\lib-a7bfaa24.js:250:31)
    at file:///X:/Coding/Garages/something/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.5/node_modules/vite/dist/node/chunks/dep-df561101.js:65946:28
    at Array.map (<anonymous>)
    at resolveConfig (file:///X:/Coding/Garages/something/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.5/node_modules/vite/dist/node/chunks/dep-df561101.js:65946:14)
    at async Module.build (file:///X:/Coding/Garages/something/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.5/node_modules/vite/dist/node/chunks/dep-df561101.js:47852:20)


Node.js v18.18.0
[debugConnector] Attaching debugger skipped (unhandled exception) Error: Command failed: X:/Coding/Garages/something/node_modules/.bin/electron-vite.CMD X:\IDEs\IntelliJ IDEA Ultimate\plugins\javascript-debugger\debugConnectorPortPublisher.js 58014
    at checkExecSyncError (node:child_process:890:11)
    at execFileSync (node:child_process:926:15)
    at Object.<anonymous> (X:\IDEs\IntelliJ IDEA Ultimate\plugins\javascript-debugger\debugConnector.js:34:3)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at internalRequire (node:internal/modules/cjs/loader:174:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1433:5) {
  status: 1,
  signal: null,
```

### Electron-Vite Version

1.0.27

### Electron Version

25.6.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
https://electron-vite.org/guide/debugging.html#webstorm

**Comment by alex8088** [comment]
https://github.com/alex8088/electron-vite/issues/130#issuecomment-1467303259

**Comment by AlexV525** [comment]
Thanks for the ref!
