### ISSUE TITLE
Error right after running `npm create @quick-start/electron`

### ISSUE THREAD

**Issue by ssantos21** [alex8088/electron-vite#359]
### Describe the bug

I am getting the error below right after running `npm create @quick-start/electron`

```
✔ Project name: … electron-react
✔ Select a framework: › react
✔ Add TypeScript? … No
✔ Add Electron updater plugin? … No
✔ Enable Electron download mirror proxy? … No


Scaffolding project in /home/node/Dev/clients/electron-react...

Done. Now run:

  cd electron-react
  npm install
  npm run dev

node@node-virtual-machine ~/D/clients (dev)> cd electron-react/
node@node-virtual-machine ~/D/c/electron-react (dev)> npm install

> electron-react@1.0.0 postinstall
> electron-builder install-app-deps

Error: Cannot find module '/home/node/Dev/clients/electron-react/node_modules/config-file-ts/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:438:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:680:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Function.Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/node/Dev/clients/electron-react/node_modules/read-config-file/src/main.ts:6:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/node/Dev/clients/electron-react/node_modules/electron-builder/src/cli/cli.ts:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
npm ERR! code 1
npm ERR! path /home/node/Dev/clients/electron-react
npm ERR! command failed
npm ERR! command sh -c electron-builder install-app-deps

npm ERR! A complete log of this run can be found in: /home/node/.npm/_logs/2023-12-24T02_18_57_896Z-debug-0.log
node@node-virtual-machine ~/D/r/m/c/electron-react (dev) [1]>
```

Despite the error, the command `npm run dev` appears to work normally.

### Electron-Vite Version

1.0.27

### Electron Version

25.6.0

### Vite Version

4.4.9

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
确保你的nodejs版本支持electron-builder

**Comment by dmitrykaigorodov** [comment]
```
npm install
```

**Comment by alex8088** [comment]
```
node@node-virtual-machine ~/D/clients (dev)> cd electron-react/
node@node-virtual-machine ~/D/c/electron-react (dev)> npm install
```

Dir path is wrong.
