### ISSUE TITLE
由better-sqlite3引发的问题

### ISSUE THREAD

**Issue by ikaroinory** [alex8088/electron-vite#398]
### Describe the bug

当运行
```
const Database = require('better-sqlite3')
const db = new Database('${path}/test.db', { verbose: console.log })
```
时，会引发错误：
```
Error: The module '...\node_modules\better-sqlite3\build\Release\better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 108. This version of Node.js requires
NODE_MODULE_VERSION 119. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:2238)
    at Module._extensions..node (node:internal/modules/cjs/loader:1356:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2238)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at l._load (node:electron/js2c/asar_bundle:2:13642)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at bindings (...\node_modules\bindings\bindings.js:112:48)
    at new Database (...\node_modules\better-sqlite3\lib\database.js:48:64) {
  code: 'ERR_DLOPEN_FAILED'
}
```
其中，项目路径已用...代替。

请问该如何解决？

### Electron-Vite Version

2.0.0

### Electron Version

28.2.0

### Vite Version

5.0.12

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
better-sqlite3 需要根据electron版本重新编译来支持electron，可自行检索如何编译better-sqlite3

**Comment by ikaroinory** [comment]
> better-sqlite3 需要根据electron版本重新编译来支持electron，可自行检索如何编译better-sqlite3，建议你在better-sqlite3的issue中查找相关问题。

感谢，我已经解决这个问题了。

**Comment by ikaroinory** [comment]
安装electron-rebuild
```
npm i --save-dev @electron/rebuild
```
进入项目目录，重新编译better-sqlite3
```
.\node_modules\.bin\electron-rebuild.cmd
```
或者
```
electron-rebuild -f -w better-sqlite3
```

**Comment by ikaroinory** [comment]
安装electron-rebuild
```
npm i --save-dev @electron/rebuild
```
进入项目目录，重新编译better-sqlite3
```
.\node_modules\.bin\electron-rebuild.cmd
```
或者
```
electron-rebuild -f -w better-sqlite3
```
