### ISSUE TITLE
集成Sentry官方的electron-vite例子后，打包报错

### ISSUE THREAD

**Issue by zmm2tysu** [alex8088/electron-vite#489]
### Describe the bug

```
error during preview electron app:
SyntaxError: [vite:bytecode] unknown file: When using '@babel/plugin-transform-arrow-functions', it's not possible to compile `super.prop` in an arrow function without compiling classes.
Please add '@babel/plugin-transform-classes' to your Babel configuration.
  12530 |         this[INTERNAL].currentSocket = socket;
  12531 |         // @ts-expect-error `createSocket()` isn't defined in `@types/node`
> 12532 |         super.createSocket(req, options, cb);
        |         ^^^^^^^^^^^^^^^^^^
  12533 |       }, cb);
  12534 |   }
  12535 |
    at File.buildCodeFrameError (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+core@7.24.4\node_modules\@babel\core\lib\transformation\file\file.js:202:12)     
    at NodePath.buildCodeFrameError (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\path\index.js:98:21)        
    at hoistFunctionEnvironment (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\path\conversion.js:219:27)      
    at NodePath.arrowFunctionToExpression (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\path\conversion.js:116:7)
    at PluginPass.ArrowFunctionExpression (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+plugin-transform-arrow-functions@7.24.1_@babel+core@7.24.4\node_modules\@babel\plugin-transform-arrow-functions\lib\index.js:18:16)
    at newFn (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\visitors.js:160:14)
    at NodePath._call (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\path\context.js:46:20)
    at NodePath.call (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\path\context.js:36:17)
    at NodePath.visit (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\path\context.js:82:31)
    at TraversalContext.visitQueue (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\context.js:89:16)
    at TraversalContext.visitMultiple (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\context.js:61:17)
    at TraversalContext.visit (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\context.js:110:19)
    at traverseNode (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at NodePath.visit (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\path\context.js:88:52)
    at TraversalContext.visitQueue (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\context.js:89:16)
    at TraversalContext.visitSingle (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\context.js:112:19)
    at traverseNode (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at NodePath.visit (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\path\context.js:88:52)
    at TraversalContext.visitQueue (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\context.js:89:16)
    at TraversalContext.visitMultiple (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\context.js:61:17)
    at TraversalContext.visit (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\context.js:110:19)
    at traverseNode (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at NodePath.visit (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\path\context.js:88:52)
    at TraversalContext.visitQueue (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\context.js:89:16)
    at TraversalContext.visitSingle (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\context.js:112:19)
    at traverseNode (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at NodePath.visit (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\path\context.js:88:52)
    at TraversalContext.visitQueue (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\context.js:89:16)
    at TraversalContext.visitMultiple (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\context.js:61:17)
    at TraversalContext.visit (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\context.js:110:19)
    at traverseNode (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at NodePath.visit (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\path\context.js:88:52)
    at TraversalContext.visitQueue (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\context.js:89:16)
    at TraversalContext.visitSingle (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\context.js:112:19)
    at traverseNode (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at NodePath.visit (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\path\context.js:88:52)
    at TraversalContext.visitQueue (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\context.js:89:16)
    at TraversalContext.visitMultiple (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\context.js:61:17)
    at TraversalContext.visit (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\context.js:110:19)
    at traverseNode (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at NodePath.visit (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\path\context.js:88:52)
    at TraversalContext.visitQueue (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\context.js:89:16)
    at TraversalContext.visitSingle (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\context.js:112:19)
    at traverseNode (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at traverse (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+traverse@7.24.1\node_modules\@babel\traverse\lib\index.js:52:34)
    at transformFile (D:\Workspace\js\desktop\car-radar-matrix\node_modules\.pnpm\@babel+core@7.24.4\node_modules\@babel\core\lib\transformation\index.js:82:31)
 ELIFECYCLE  Command failed with exit code 1.
```
***
注释掉主线程中引入的@sentry/electron/main的init方法或者关闭源代码保护则打包成功

尝试过以下配置，没起作用
```
export default defineConfg({
      ......
      renderer: {
          plugins: [react({ babel: { plugins: ['@babel/plugin-transform-classes'] } })],
      }
})
```
***
完整配置文件

```
import react from '@vitejs/plugin-react'
import { bytecodePlugin, defineConfig, externalizeDepsPlugin } from 'electron-vite'
import { resolve } from 'path'

export default defineConfig({
  main: {
    plugins: [externalizeDepsPlugin(), bytecodePlugin()]
  },
  preload: {
    plugins: [externalizeDepsPlugin(), bytecodePlugin()],
    build: {
      rollupOptions: {
        input: {
          index: resolve(__dirname, 'src/preload/index.ts'),
          webview: resolve(__dirname, 'src/preload/webview.ts')
        }
      }
    }
  },
  renderer: {
    resolve: {
      alias: {
        '@renderer': resolve('src/renderer')
      }
    },
    plugins: [react({ babel: { plugins: ['@babel/plugin-transform-classes'] } })],
    build: {
      // sourcemap: true,
      minify: true,
      rollupOptions: {
        output: {
          // minifyInternalExports: true
          manualChunks: (id) => {
            // if (!id.includes('node_modules')) {
            //   console.log(id, getModuleInfo(id))
            // }
            if (id.includes('node_modules')) {
              return 'vendor'
            } else if (id.includes('/renderer/pages')) {
              return `chunk`
            } else {
              return 'index'
            }
          }
        }
      }
    }
  }
})

```

### Electron-Vite Version

2.1.0

### Electron Version

28.2.0

### Vite Version

5.0.12

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
此问题与renderer无关，通常都无需去构建第三方模块，请将sentry相关模块安装在dep中。
