### ISSUE TITLE
Bug: Automatic update error in Linux  (0 , builder_util_runtime_1.retry) is not a function

### ISSUE THREAD

**Issue by Ares-Chang** [alex8088/electron-vite#658]
### Describe the bug

Automatic update error reporting under Linux system

![image](https://github.com/user-attachments/assets/babfa44f-7e2b-4ced-a69e-a7c5c3ec1290)

Automatic update error in Linux The update mode I choose is generic update

![image](https://github.com/user-attachments/assets/7ef897d0-3393-45f9-9846-9d51ddc250aa)

My update code has only one checkForUpdatesAndNotify just to detect and update under

![image](https://github.com/user-attachments/assets/4aa3bfee-2a37-4383-9d7c-92fb2256efa5)

I'm not sure if this is a problem with my use or a problem with the electron-updater packaging

Installing the builder-util-runtime manually solves the problem perfectly

I tried to run a demo under electron-updater but failed, I am a novice

 So I reported the issues here, hoping to help others, or add this dependency

 Thanks!

### Electron-Vite Version

2.3.0

### Electron Version

31.0.2

### Vite Version

5.3.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://electron-vite.org).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by AntonNevsgodov** [comment]
Same on MacOS
```
[2024-11-19 18:52:29.154] [error] (AutoUpdateService)   Error: TypeError: (0 , builder_util_runtime_1.retry) is not a function
    at MacUpdater.executeDownload (/Applications/MyApp.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:567:52)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-11-19 18:52:29.155] [error]                       Unhandled rejection TypeError: (0 , builder_util_runtime_1.retry) is not a function
    at MacUpdater.executeDownload (/Applications/MyApp.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:567:52)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
   ```

**Comment by Ares-Chang** [comment]
**Installing the `builder-util-runtime` package manually solves the problem perfectly**

This is supposed to be an upstream warehouse problem, but I can't run the mini repo

**Comment by HQidea** [comment]
same on Windows
```
[2024-11-21T16:08:47.776] [ERROR] default - Error: TypeError: (0 , builder_util_runtime_1.retry) is not a function
    at NsisUpdater.executeDownload (C:\Users\path\to\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:567:52)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by oneQiu** [comment]
+1 我也一样 mac

**Comment by huangkairan** [comment]
same

**Comment by huangkairan** [comment]
> **Installing the `builder-util-runtime` package manually solves the problem perfectly**
> 
> This is supposed to be an upstream warehouse problem, but I can't run the mini repo

thx, it works

**Comment by alex8088** [comment]
Issues should be reported to electron-updater
